@Nikita_Yarancev_kt_31_23_HostAddress = http://localhost:5234

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Specialties
Content-Type: application/json

{ "title": "Информатика и вычислительная техника", "code": "09.03.01" }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Groups
Content-Type: application/json

{ "name": "KT-31-23", "course": 3, "year": 2023, "specialtyId": 1 }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Groups/filter
Content-Type: application/json

{ "specialtyId": 1, "year": 2023, "isDeleted": false }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Students
Content-Type: application/json

{ "lastName": "Иванов", "firstName": "Иван", "middleName": "Иванович", "groupId": 1 }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Students/filter
Content-Type: application/json

{ "groupName": "KT-31-23", "fio": "иванов", "isDeleted": false }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Disciplines
Content-Type: application/json

{ "name": "Математика", "direction": "Technical" }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Disciplines/filter
Content-Type: application/json

{ "direction": "Technical", "isDeleted": false }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Grades
Content-Type: application/json

{ "studentId": 1, "disciplineId": 1, "value": 5, "date": "2025-01-15" }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Grades/average/group-discipline
Content-Type: application/json

{ "groupId": 1, "disciplineId": 1 }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Grades/average/year
Content-Type: application/json

{ "year": 2025 }

###

POST {{Nikita_Yarancev_kt_31_23_HostAddress}}/Credits
Content-Type: application/json

{ "studentId": 1, "disciplineId": 1, "isPassed": true, "date": "2025-01-10" }

###

DELETE {{Nikita_Yarancev_kt_31_23_HostAddress}}/Groups/1

###
